server:
  port: 8003
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  servlet:
    multipart:
      max-file-size: 500MB #设置上传单个文件最大容量
      max-request-size: 500MB #设置总上传最大容量
  application:
    name: service-vod
  profiles:
    active: dev

aliyun:
  vod:
    file:
      keyid:
      keysecret:

