server:
  port: 8006
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-msm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 1234
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 1800000
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
        #设置json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail: #邮箱配置
    host: smtp.qq.com #使用SSL，端口号465或587 发送邮件的服务器
    username: #使用邮箱的账号
    password: #开启IMAP/SMTP服务的授权码
    default-encoding: utf-8
mybatis-plus:
  mapper-locations: classpath:com/cqy/cmsservice/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl