server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#阿里云oss
aliyun:
  oss:
    file:
      # 地域节点
      endpoint:
      # id
      key-id:
      # 密钥
      key-secret:
      # bucket的名称
      bucket-name: